<div class="page-intro">
    <div><span class="eyebrow"><i data-lucide="sparkles"></i> WORKSPACE</span><h1>Xin chào, <?= e($user['name']) ?></h1><p>Mọi hoạt động mua hàng, số dư và dịch vụ đều được gom trong một nơi.</p></div>
    <a class="button button-primary" href="<?= e(url('/app/catalog')) ?>"><i data-lucide="arrow-up-right"></i> Khám phá sản phẩm</a>
</div>
<div class="stat-grid">
    <div class="stat-card"><span class="stat-icon tone-teal"><i data-lucide="wallet"></i></span><span>Số dư ví</span><strong><?= e(format_money($user['balance'])) ?></strong><small>Được cập nhật theo giao dịch</small></div>
    <div class="stat-card"><span class="stat-icon tone-blue"><i data-lucide="receipt-text"></i></span><span>Tổng đơn hàng</span><strong><?= e($stats['orders']) ?></strong><small><?= e($stats['processing_orders']) ?> đơn đang xử lý</small></div>
    <div class="stat-card"><span class="stat-icon tone-amber"><i data-lucide="network"></i></span><span>Proxy hoạt động</span><strong><?= e($stats['active_proxies']) ?></strong><small>Gia hạn trước khi hết hạn</small></div>
    <div class="stat-card"><span class="stat-icon tone-violet"><i data-lucide="badge-check"></i></span><span>Yêu cầu dịch vụ</span><strong><?= e($stats['social_requests']) ?></strong><small>Đang chờ xử lý</small></div>
</div>
<div class="dashboard-grid">
    <section class="panel"><div class="panel-heading"><div><span class="eyebrow">TRUY CẬP NHANH</span><h2>Luồng làm việc</h2></div></div><div class="quick-grid"><a class="quick-link" href="<?= e(url('/app/proxy')) ?>"><i data-lucide="network"></i><span><strong>Mua Proxy</strong><small>Cấu hình và xem giá</small></span><i data-lucide="arrow-up-right"></i></a><a class="quick-link" href="<?= e(url('/app/social')) ?>"><i data-lucide="badge-check"></i><span><strong>Dịch vụ mạng xã hội</strong><small>Gửi yêu cầu an toàn</small></span><i data-lucide="arrow-up-right"></i></a><a class="quick-link" href="<?= e(url('/app/wallet')) ?>"><i data-lucide="wallet-cards"></i><span><strong>Nạp tiền</strong><small>Đối soát rõ ràng</small></span><i data-lucide="arrow-up-right"></i></a><a class="quick-link" href="<?= e(url('/app/orders')) ?>"><i data-lucide="receipt"></i><span><strong>Lịch sử đơn</strong><small>Xem trạng thái và mã đơn</small></span><i data-lucide="arrow-up-right"></i></a></div></section>
    <section class="panel"><div class="panel-heading"><div><span class="eyebrow">HOẠT ĐỘNG</span><h2>Giao dịch gần đây</h2></div><a class="text-link" href="<?= e(url('/app/wallet')) ?>">Xem ví</a></div><?php if (($stats['recent_activity'] ?? []) !== []): ?><div class="activity-list"><?php foreach ($stats['recent_activity'] as $activity): ?><div class="activity-row"><span class="activity-icon <?= $activity['kind'] === 'credit' ? 'is-credit' : 'is-debit' ?>"><i data-lucide="<?= $activity['kind'] === 'credit' ? 'arrow-down-left' : 'arrow-up-right' ?>"></i></span><span><strong><?= e($activity['description']) ?></strong><small><?= e(format_date($activity['created_at'])) ?></small></span><b><?= $activity['kind'] === 'credit' ? '+' : '-' ?><?= e(format_money($activity['amount'])) ?></b></div><?php endforeach; ?></div><?php else: ?><div class="empty-inline"><i data-lucide="activity"></i><span>Chưa có giao dịch nào.</span></div><?php endif; ?></section>
</div>
